### ISSUE TITLE
数据预处理疑问

### ISSUE THREAD

**Issue by whlcode-2001** [liuqidong07/LLM-ESR#2]
作者您好：
    我在使用官网下载的yelp数据集，data_process.py后，再get_item_embedding.ipynb 发现报错：
![屏幕截图 2024-11-27 003154](https://github.com/user-attachments/assets/46bc4807-552d-404a-a6e6-729a50b920fc)
似乎并没有id为Pz...的这一项，可能是更新数据集了吗？
而且存在value["categories"]=None的值。
发现并没有type列，open列是is_open
    item_str = item_str.replace("<TYPE>", value["type"])    
    item_str = item_str.replace("<OPEN>", str(value["open"]))
{'business_id': 'lk9IwjZXqUMqqOhM774DtQ',
 'name': 'Caviar & Bananas',
 'address': '2031 Broadway',
 'city': 'Nashville',
 'state': 'TN',
 'postal_code': '37203',
 'latitude': 36.1483712,
 'longitude': -86.7988947,
 'stars': 3.5,
 'review_count': 159,
 'is_open': 0,
 'attributes': {'RestaurantsTakeOut': 'True',

关于调用这个api:
import requests
import json
url = ""
payload = json.dumps({
   "model": "text-embedding-ada-002",
   "input": "The food was delicious and the waiter..."
})
headers = {
   'Authorization': '',
   'User-Agent': 'Apifox/1.0.0 (https://apifox.com)',
   'Content-Type': 'application/json'
}
response = requests.request("POST", url, headers=headers, data=payload)
能否再详细的介绍一下。
谢谢您的解答！！

**Comment by liuqidong07** [comment]
您好，感谢对我们论文关注。我也不太清楚是否是因为数据集更新了？您可以发我您的邮箱，我把我使用的原始数据发送给您。

祝好

**Comment by cjjcjjcjj** [comment]
> 您好，感谢对我们论文关注。我也不太清楚是否是因为数据集更新了？您可以发我您的邮箱，我把我使用的原始数据发送给您。
> 
> 祝好

作者您好，对您的工作很感兴趣，能否也发一份三个数据集的原始数据给我，下面是我的邮箱：chenjiajie00@163.com。
感谢！
祝好

**Comment by whlcode-2001** [comment]
感谢您的回复！ 我的邮箱是: wanghl0224@163.com   劳烦您发一份，谢谢！

**Comment by liuqidong07** [comment]
@whlcode-2001 哈喽，我把数据传到google drive上了。链接：https://drive.google.com/file/d/1ErhY0KOloWNHgBtVoYVDNSkhgA9r1dE_/view?usp=drive_link

祝好

**Comment by whlcode-2001** [comment]
@liuqidong07 谢谢您！我已申请访问权限，或许可能您那边需要修改一下google drive权限~
祝好！

**Comment by liuqidong07** [comment]
@whlcode-2001 抱歉！我忘记设置权限了，现在应该可以了！

祝好

**Comment by GithubX-F** [comment]
> [@whlcode-2001](https://github.com/whlcode-2001) 抱歉！我忘记设置权限了，现在应该可以了！
> 
> 祝好

大佬，方便发一下其他2份原始数据集吗？ 感谢

**Comment by Xiaozhiyao** [comment]
附议，请问大佬方便发一下其它的原始数据集吗
